### PR TITLE
V1850

### PR DESCRIPTION
**Pull request by thareUSGS**
## Summary

v 1.8.5.0 T.Hare   
- Added choice between Internal_Reference/External_Reference in Video class, created reference rules for it also    
- Added rule for Tile Internal_Reference for reference type to be "data_to_tile_source_data"    
- Added "H.264 Frame" enumeration to onboard_compression_type    
- Updated definition to specify only unsigned integer are valid to have a sample_bit_mask (need to still add rule)    
- Updated definition for tile_num_bands

### CODE REVIEW

**Comment by thareUSGS** [comment]
minor updates and added a few rules. Should be 100% backwards compat.

**Comment by jordanpadams** [comment]
@thareUSGS did you want this to be in this build cycle?

**Comment by thareUSGS** [comment]
if not too late -- and I didn't mess anything up with my pull requests

**Comment by jordanpadams** [comment]
@thareUSGS unfortunately, this is where the process kind of falls apart. once a PR is made for the release, ideally any changes you need to make would go directly into that branch, or things can get a little kludgy. not the end of the world, but basically we just tagged a release with the old version: https://github.com/pds-data-dictionaries/ldd-img/releases/tag/1G00_1840, will need to merge this branch, and then create another branch to tag another release for v1850

**Comment by thareUSGS** [comment]
Okay - can do 1850 updates again, not many to add. Can you tag the release 1G00_1840?

**Comment by jordanpadams** [comment]
@thareUSGS we are good to go. do we want to tag DISP and CART as well?

**Pull request merged**
